version: "3"
services:
  nginx:
    build: 
      context: ./requirements/nginx/.
    ports:
      - "3000:443"
    volumes:
      - WordPress:/var/www/html
    networks:
      - mynetwork
    links:
      - "wordpress"
  
  wordpress:
    build:
      context: ./requirements/wordpress/.
    ports:
      - "9000:9000"
    volumes:
      - "WordPress:/var/www/html"
    networks:
      - mynetwork
    links:
      - "mariadb"

  mariadb:
    build:
      context: ./requirements/mariadb/.
    ports:
      - "3306:3306"
    volumes:
      - "DB:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - mynetwork

volumes:
  WordPress:
  DB:

networks:
  mynetwork:
