version: "3"
services:
  nginx:
    build: 
      context: ./requirements/nginx/.
    networks:
      - mynetwork
    ports:
      - "3000:443"
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - "wordpress"
  
  wordpress:
    build:
      context: ./requirements/wordpress/.
    networks:
      - mynetwork
    ports:
      - "3000:9000"
    expose:
      - 9000
      - 3306
    volumes:
      - "WordPress:/var/www/html"
    depends_on:
      - mariadb
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  mariadb:
    build:
      context: ./requirements/mariadb/.
    networks:
      - mynetwork
    expose:
      - 3306
    volumes:
      - "DB:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  WordPress:
  DB:

networks:
  mynetwork:
