version: "3"
services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/.
    networks:
      - mynetwork
    ports:
      - "5000:443"
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - "wordpress"
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
    networks:
      - mynetwork
    expose:
      - 9000
    volumes:
      - "WordPress:/var/www/html"
    depends_on:
      - mariadb
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/.
    networks:
      - mynetwork
    expose:
      - 3306
    volumes:
      - "DB:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: '/Users/aaitouna/data/wordpress'
  DB:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: '/Users/aaitouna/data/mariadb'

networks:
  mynetwork:
    driver: bridge
